version: "3.4"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: shortcodes
    restart: always
    build: ./
    volumes:
      - ./:/usr/app
    ports:
      - "4000:4000"
      - "9229:9229"
    links:
      - mongo